### ISSUE TITLE
Broken ProfilePreview.tsx component

### ISSUE THREAD

**Issue by tantodefi** [lukso-network/tools-dapp-boilerplate#11]
When I connect UP It's correctly displaying my UP address but not updating my profile image or other metadata in the component; I was wondering if this was due to the recent changes to verifiableURL... I haven't explored this myself yet.
No errors in the console.

![Screenshot 2023-12-27 at 5 02 21 PM](https://github.com/lukso-network/tools-dapp-boilerplate/assets/107724252/bf1fb0ea-35c4-4bcd-a7e7-b382f45b9fd9)

**Comment by Hugoo** [comment]
Hey thanks - yeah this is very likely because of outdated lib. We I'll check this starting next week.

**Comment by tantodefi** [comment]
Wow thanks so much for the quick fix! 
Gonna try it now

**Comment by fhildeb** [comment]
Hey @tantodefi,

I have been investigating this issue for the last two days- checking storage, networks, and browsers. Here are the outcomes: 

## Investigation

The bug is unrelated to our IPFS RPCs. I've checked the IPFS links separately, and everything works flawlessly there. Both the testnet and mainnet use the same address. 

The `ProfilePreview` stays empty because of the missing provider object. Currently, the Universal Profile Browser Extension officially only supports `Chrome`. Here, the app has no issues connecting to the correct network and showing data on the ProfilePreview component. However, there is an issue when using `Opera`, `Firefox`, or potentially other unsupported browsers: The extension and network data are not adequately injected into the `window.ethereum` object used across this repository. 

> I'm assuming you're using such a browser because I could not reproduce this issue elsewhere for both testnet and mainnet profiles.

## Bugfix

I've talked back to the extension team: Instead of relying on the `window.ethereum` object, its recommended to use the `window.lukso` object. If dApps wants to allow for both regular wallets and the Universal Profile Browser Extension, it is recommended to add a fallback to the regular `wallet.ethereum` whenever `wallet.lukso` is unavailable.

As this dApp acts as a reference implementation for developers on LUKSO, I've applied those changes to the repository in the following PR: #12 (referenced above). This issue should now be resolved.

✅ Successfully tested within `Chrome`, `Opera`, `Firefox`
✅ Verified all functionality on network switches and context updates.
🗃️ Added an internal ticket, so the bug can be resolved in future releases.  

## Screenshots

![img1](https://github.com/lukso-network/tools-dapp-boilerplate/assets/61689369/16cd55d6-c9ec-4216-a107-d350f289e19b)
![img2](https://github.com/lukso-network/tools-dapp-boilerplate/assets/61689369/84104d1e-5b36-4d6c-92de-7bb3c60b06f0)

## What next?

👉🏻 This PR will be closed as soon as I merge #12. Feel free to test and give further feedback.
👉🏻 I will add our RPC endpoints to the [Network Parameters](https://docs.lukso.tech/networks/mainnet/parameters) for better clarity.
👉🏻 I will update the [Connection Guide](https://docs.lukso.tech/learn/dapp-developer/connect-profile) to the new provider setup.

Thanks again for the valuable feedback. This definitely helped us 🙏🏻
